# -*- coding: utf-8 -*-
"""Projeto Ebac.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RtlUUhQdSu0ryoVZOcgG5FjpnDkS_e9e
"""

#Início da operação

#calcular média de notas de uma instituição

Aluno = input("Insira o nome do aluno: ")

notas = [float(input('Digite a nota 1: ')),
         float(input('Digite a nota 2: ')),
         float(input("Digite a nota 3: ")),
         float(input("Digite a nota 4: "))]
soma = 0

for nota in notas:
  soma += nota
media = soma / len(notas)

if media >= 7:
    print("A média final do aluno", Aluno, " é: ", round(media, 2), ". Aluno aprovado.")
else:
    print("A média final do aluno", Aluno+ " é: ", round(media, 2), ". Aluno reprovado.")